## Numpy Array operations

In [2]:
import numpy as np

In [4]:
arr=np.array([1,2,3,4,5,6,7,8,9,10])
print("Basic Slicing : ",arr[2:7])
print("With Step",arr[1:8:2])
print("Negative Indexing",arr[-3])

Basic Slicing :  [3 4 5 6 7]
With Step [2 4 6 8]
Negative Indexing 8


In [5]:
arr_2d=np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])
print("Specific Element : ",arr_2d[1,2])
print("Entire Row : ",arr_2d[1])
print("Entire Column : ",arr_2d[:,1]) # : represents all ros because to get a particular column we need all the rows

Specific Element :  6
Entire Row :  [4 5 6]
Entire Column :  [2 5 8]


### Sorting

In [ ]:
unsorted=np.array([3,2,7,4,2,8,1])
print("Sorted array : ",np.sort(unsorted))

unsorted_2d=np.array([[7,4,6],
                      [1,9,3],
                      [5,2,7]])
# here sorting can be either row wise(axis=1) or column wise(axis=0) 
print("Sorted 2D array column wise : ",np.sort(unsorted_2d,axis=0))
print("Sorted 2D array row wise : ",np.sort(unsorted_2d,axis=1))

Sorted array :  [1 2 2 3 4 7 8]
Sorted 2D array :  [[1 2 3]
 [5 4 6]
 [7 9 7]]


### Filter

In [8]:
# numpy array allows us to write expressions in an array
number=np.array([1,2,3,4,5,6,7,8,9,10]) 
even_number=number[number%2==0] # this is an even number array from 1 to 10
print(even_number)

[ 2  4  6  8 10]


### Filter with mask

In [11]:
# in the above expression number%2=0 is a mask 
mask=number>5
print("Numbers greater than 5 : ",number[mask])

Numbers greater than 5 :  [ 6  7  8  9 10]


### Fancy indexing vs np.where()

In [ ]:
indices=[0,2,4]
print(number[indices])

# np.where()

where_result=np.where(number>5) # similar to masking , it stores the indices(fulfilling required condition) in an array
print("Numbers > 5 : ",number[where_result])

[1 3 5]
Number > 5 :  [ 6  7  8  9 10]


In [ ]:
condition_arr1=np.where(number>5,number*4,number)
print(condition_arr1)
# to understand this we can see it in this way - 
# if(number>5){
#     number*4
# }
# else{
#     number
# }
condition_arr2=np.where(number>5,"true","false")
print(condition_arr2)

[ 1  2  3  4  5 24 28 32 36 40]
['false' 'false' 'false' 'false' 'false' 'true' 'true' 'true' 'true'
 'true']


### Adding and removing data

In [18]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
combined=np.concatenate((arr1,arr2)) # passing as a Tuple
print(combined)

[1 2 3 4 5 6]


### Array compatibility

In [ ]:
a=np.array([1,2,3])
b=np.array([4,5,6,7])
c=np.array([7,8,9])

print('compatibility shapes',a.shape==b.shape)

compatibility shapes True


In [21]:
# vstack() (vertical stack always adds a new row)

original=np.array([[1,2],[3,4]])
new_row=np.array([[5,6]])
new_arr=np.vstack((original,new_row))
print(new_arr)

# hstack() (horizontal stack)

new_col=np.array([[5],[6]])
new_arr=np.hstack((original,new_col))
print(new_arr)

[[1 2]
 [3 4]
 [5 6]]
[[1 2 5]
 [3 4 6]]


In [ ]:
# deleting elements

arr=np.array([1,2,3,4,5])
deleted=np.delete(arr,4) # here 4 is the index
print("Array after deletion : ",deleted)

Array after deletion :  [1 2 3 4]
